In [1]:
def gcdOfStrings( str1: str, str2: str) -> str:
    # Check if concatenated strings are equal or not, if not return ""
    if str1 + str2 != str2 + str1:
        return ""
    # If strings are equal than return the substring from 0 to gcd of size(str1), size(str2)
    from math import gcd
    
    print(f"s1: {len(str1)}, s2: {len(str2)}")
    return str1[:gcd(len(str1), len(str2))]

In [2]:
import math
from math import gcd
gcd(10,12)

2

In [3]:
gcdOfStrings("ABABAB","AB")

s1: 6, s2: 2


'AB'

In [10]:
import numpy as np

In [11]:
a = [[1,2,3], 
     [4,5,6],
     [7,8,9]]
print(a)




[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [12]:
a= np.array(a)

In [13]:
x1 = np.random.randint(10, size=(3,4))  # One-dimensional array
x1

array([[9, 3, 8, 9],
       [0, 2, 1, 8],
       [4, 8, 5, 9]])

In [14]:
x1.ndim

2

In [15]:
x2 = np.random.randint(10, size=(3,3,3))  # One-dimensional array
x2.ndim

3

In [16]:
rows= a.shape[0]
cols= a.shape[1]

rows, cols

(3, 3)

In [20]:
a = np.random.randint(10, size=(3,3))  # One-dimensional array
print(a)
for i in range(rows * cols):
    print(f" {a[i//cols][i%cols]}", end="\t")


[[3 9 5]
 [9 8 0]
 [8 6 6]]
 3	 9	 5	 9	 8	 0	 8	 6	 6	

In [ ]:
a = np.random.randint(10, size=(3,4))  # One-dimensional array
a

In [26]:
11/3, 11.5//3

(3.6666666666666665, 3.0)